### ISSUE TITLE
Consider splitting IRequestHandler<TRequest, TResponse> into two interfaces

### ISSUE THREAD

**Issue by dotnetjunkie** [christophdebaene/CleanArchitecture#5]
Generic abstractions are often defined for architectural artefacts. This means that everything that belongs to the same architectural concept, should typically be placed behind that same abstraction. This makes code really clean and gives some sort of 'architectural domain language' to communicate between developers.

In my opinion, commands and queries are two completely different concept. Commands mutate state and don't return data. Queries return data, but don't return state. This makes it really useful to make this strict separation in code with the interfaces as well.

Another way to look at this is from the view point of cross-cutting concerns. Those generic abstractions are usually the place where cross-cutting concerns are applied. This project defines decorators around `IRequestHandler<,>` to apply cross-cutting concerns. But commands and queries both often require a different set of cross-cutting concerns. Queries need caching and performance measuring, while commands need transaction handling, validation, handling of business rules, deadlock retry handling, audit trailing and deduplication. Letting commands and queries share the same generic abstraction means that most decorators need to be applied conditionally (which increases complexity and is impossible to achieve with most DI containers and [Pure DI](http://blog.ploeh.dk/2014/06/10/pure-di/)), or the conditional checks need to be implemented inside the decorator itself (which is ugly).

So from both an architectural and practical point of view, it is wise to consider splitting the `IRequestHandler<TRequest, TResponse>` interface into an `ICommandHandler<TCommand>` and `IQueryHandler<TQuery, TResult>` interface.

**Comment by christophdebaene** [comment]
In my previous projects I used the `ICommandHandler<TCommand>` and `IQueryHandler<TQuery, TResult>` interfaces and currently I am using `IRequestHandler<TRequest, TResponse>` interface.

Obviously the big advantage is that you have a common interface, that's why we're using [Command Oriented Interface](http://martinfowler.com/bliki/CommandOrientedInterface.html) and applying [decorated commands](http://martinfowler.com/bliki/DecoratedCommand.html). Indeed the re-usability isn't that big between command and query decorators. Like always it's a trade-off....

Initially I hesitated to show the sample solution through `ICommandHandler<TCommand>` and `IQueryHandler<TQuery, TResult>` or `IRequestHandler<TRequest, TResponse>`.

I know we shouldn't do it, but there are some cases (due to legacy, constraints, ...) that a command need to return data. In that case I like more the approach of `IRequestHandler<TRequest, TResponse>` because it still cleanly separates the `request` and the `response`. Otherwise you need to do something similar like you mention [here](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=93). In that case from a signature point of view it's not clear that the command returns data, whether the `IRequestHandler<TRequest, TResponse>` interface is always very explicit about that, can be a `Unit` or a generated response id.

**Comment by dotnetjunkie** [comment]
I really wished I hadn't written [this](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=93) article, but I admitted my mistake and added a read note at the start of the article to make that clear.

At least you are well aware of the downsides of having a single interface and are making a very explicit trade-off, considering you're building on top of a legacy system.

**Comment by mrchief** [comment]
Speaking of legacy systems, I think Oracle spoiled everyone with `Update` [`Returning Into`](https://docs.oracle.com/cd/B19306_01/appdev.102/b14261/returninginto_clause.htm). Its too tempting to not have one query instead of 2! 

I have the same thing for same reasons! :laughing:

**Comment by mrchief** [comment]
What was the resolution?

**Comment by christophdebaene** [comment]
I am still in favor of having a common interface and that in some circumstances you need to return data from a command.
What I do to make it more explicit is by decorating the request through an attribute (`Command` or `Query`).

```csharp
[Command]
public record CreateNewTask : IRequest<Unit>
{
   public Guid TodoId { get; init; }
   public string Title { get; init; }
}

[Query]
public record GetTodoDetail : IRequest<TodoDetailModel>
{
    public Guid TodoId { get; init; }
}
```

That way you can also filter out some decorators that are specific to a command, for example `Transaction`.
But also reuse decorators like logging and validation despite `Command` or  `Query`.

```csharp
if (request.GetType().IsCommand())
{
    using (var scope = new TransactionScope(TransactionScopeOption.Required)
    {
        var response = await next();
        scope.Complete();
        return response;
    }
}
else
{
    return await next();
}
```

I updated the sample to illustrate this.
